### PR TITLE
Fix content typos

### PR DESCRIPTION
**Pull request by buinauskas**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

While reading metrics documentation, I've noticed some typos - let's fix them.

### CODE REVIEW

**Comment by kkraune** [comment]
Thanks! The metrics reference is actually generated from code, so the typo is in https://github.com/vespa-engine/vespa/blob/master/metrics/src/main/java/ai/vespa/metrics/ContainerMetrics.java#L130 - you can make a PR here. This first one can be merged as-is

**Comment by buinauskas** [comment]
I did submit a change in https://github.com/vespa-engine/vespa/pull/28147, I assume I can close this one down then.

**Comment by kkraune** [comment]
I will merge the full PR - as mentioned, the 3 files will be overwritten at next metrics ref generation, just make it comment here whether you will make the PR for that or I can do

**Comment by kkraune** [comment]
ok, i see that now. merging this one too!

**Pull request merged**
