### PR TITLE
Change some function signatures to make them more unified

### PR DESCRIPTION
**Pull request by theodorklauritzen**
This will make the documentation easier to integrate with the LSP

### CODE REVIEW

**Comment by kkraune** [comment]
while at it, I don't think space is a good idea in the id values, so wrong to begin with, so better replace the spaces with -

**Comment by theodorklauritzen** [comment]
@kkraune I have removed the spaces in the ids, however I think the ids is easier to read without the dash.

**Comment by kkraune** [comment]
Thanks! we have a convention to always lowercase, and replace whitespace/non-chars with dashes.

**Comment by theodorklauritzen** [comment]
I've only changes four ids, and they are listed bellow. I think to insert dashes instead of spaces would be ugly in all of these cases. In the cases the dash should be right after a ','.

`tokenInputIds(length, input_1, input_2, ...)` -> `tokenInputIds(length,input,...)`

`customTokenInputIds(start_sequence_id, sep_sequence_id, length, input_1, input_2, ...)` -> `customTokenInputIds(startSequenceId,sepSequenceId,length,input,...)`

`tokenTypeIds(length, input_1, input_2, ...)` -> `tokenTypeIds(length,input,...)`

`tokenAttentionMask(length, input_1, input_2, ...)` -> `tokenAttentionMask(length,input,...)`

I have also changes the arguments from snake case to camel case, since everything else on this page is in camel case. Before the change all arguments with multiple words was in snake case. However there ware only four occurrences of snake case, and they are shown above.

**Pull request closed without merging**
