### PR TITLE
Document from-disk

### PR DESCRIPTION
**Pull request by bratseth**
@baldersheim please review

### CODE REVIEW

**Comment by bratseth** [comment]
@baldersheim ping

**Comment by baldersheim** [comment]
Merge at will

**Comment by baldersheim** [comment]
I guess it can not be merged until the code changes are merged to master. I think they are only on the 7 branch

**Comment by baldersheim** [comment]
Merging as https://github.com/vespa-engine/vespa/pull/7291 is merged

**Pull request merged**
