### PR TITLE
Document conditional Put with create-if-nonexistent

### PR DESCRIPTION
**Pull request by vekterli**
@kkraune please review. Should not be merged before the underlying feature is enabled by default (will probably patch in required Vespa version at that point).

Also clean up some use of explicit tables for layout and replace with equivalent Denali CSS classes.

### CODE REVIEW

**Review by kkraune — APPROVED** [review]
Great!

**Comment by vekterli** [comment]
@kkraune the features required for conditional put+create to work are now enabled by default in the freshly squeezed Open-Source release. Added a few notes on supported version. PTAL.

**Comment by kkraune** [comment]
Great - merging!

**Comment by kkraune** [comment]
or you merge, the label is still there

**Pull request merged**
