### PR TITLE
Bbratseth/quickstart improvements

### PR DESCRIPTION
**Pull request by bratseth**
@jobergum please review

### CODE REVIEW

**Comment by bratseth** [comment]
@lesters it seems that the documentation rep is doing the testing of the sample-apps repo such that PRs on documentation fails when sample-apps are wrong, but sample-apps does not?

**Comment by lesters** [comment]
@bratseth Well, the sample-apps testing is just building and running unit tests, while the doc testing is more of a integration / system test.

**Comment by bratseth** [comment]
But don't you think the unit tests of the sample-apps repo should be in the sample-apps repo?

**Comment by bratseth** [comment]
Ok, maybe it's fine. Looks to me that it is only testing the sample-apps but didn't look to carefully.

**Comment by lesters** [comment]
Yes, well, that is mostly true 😄 : https://github.com/vespa-engine/documentation/blob/master/test/_test_config.yml

Currently, only quick start is tested in addition to sample apps. I'm in the process of adding tutorials as well to that list.

**Pull request merged**
