### PR TITLE
Add operating system to list of prerequisites.

### PR DESCRIPTION
**Pull request by geirst**
@vekterli please review

### CODE REVIEW

**Comment by bratseth** [comment]
What is it about the Docker quickstart that doesn't work on Windows?

**Comment by geirst** [comment]
Port forwarding. And some other trouble to get docker working in the first place

**Comment by bratseth** [comment]
Can somebody who owns a windows machine look into creating a windows version - @hakonhall ?

**Comment by hakonhall** [comment]
I don't have one - @lesters , were you able to find anyone with a windows machine?

**Comment by lesters** [comment]
No, I wasn't. However, I do have one at home for which I can use to take a look at this.

**Pull request merged**
