### PR TITLE
Revert "add bundle and close searcher tag"

### PR DESCRIPTION
**Pull request by bjormel**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by bjormel** [comment]
https://github.com/vespa-engine/vespa/pull/29512

**Review by andreer — APPROVED** [review]

**Comment by andreer** [comment]
Let's wait to merge this until we have the fix in the latest release

**Review by gjoranv — APPROVED** [review]
:

**Comment by kkraune** [comment]
should we merge this now?

**Comment by andreer** [comment]
Yes 👍

**Pull request merged**
