### PR TITLE
fix blog-app to blog-job

### PR DESCRIPTION
**Pull request by neuhausler**
tiny fix in documentation

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by kkraune** [comment]
Hi! plmk once the CLA is signed and I can merge :-)

**Comment by neuhausler** [comment]
Just signed it. Had to have it looked over by our legal team.

**Comment by kkraune** [comment]
Thanks a lot for fixing!

**Pull request merged**
