### PR TITLE
Run the multiple-bundles example

### PR DESCRIPTION
**Pull request by gjoranv**

### CODE REVIEW

**Comment by lesters** [comment]
PR build error:

```
ERROR: Expected output '200 OK' not found in command 'curl -s --head http://localhost:8080/ApplicationStatus'. Waited for 300 seconds.
ERROR: One or more files failed: https://raw.githubusercontent.com/vespa-engine/sample-apps/master/multiple-bundles/README.md
```

**Comment by gjoranv** [comment]
Fixed in https://github.com/vespa-engine/sample-apps/pull/149

**Comment by kkraune** [comment]
merge?

**Comment by kkraune** [comment]
@gjoranv ready for merge?

**Pull request merged**
