### PR TITLE
Experiment with links in headings

### PR DESCRIPTION
**Pull request by kkraune**
- added to https://docs.vespa.ai/en/overview.html so we can dry-run it there
- this adds a link in headers when hovering over, a la readme-files on GitHub and others

... or @frodelu

### CODE REVIEW

**Review by frodelu — APPROVED** [review]
As a Javascript-way this would probably work so seems OK. Ideally, I had hoped we could do this process time, but I haven't found a smooth way to do that with Jekyll yet.

**Comment by frodelu** [comment]
Leaving it up to you to merge when ready, @kkraune …

**Comment by kkraune** [comment]
Agreed, it would be better to add this when building the site. some Ruby processing / liquid, will think of it

**Comment by kkraune** [comment]
note to self: looks ok, but add check for empty id, don't add then. we could auto-generate the id if not already set, too, but that makes auto link checking harder, so probably not (another argument for doing this at site build time). otoh, setting manually will resolve links in IDE when writing -> keep manual.

**Pull request merged**
