### PR TITLE
Mention the safe startup option

### PR DESCRIPTION
**Pull request by kkraune**
@arnej27959 : the docs says "The safe mode is disabled by default" - but it seems is is default on for self-hosted Vespa, ref https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA#start-the-admin-server ?

### CODE REVIEW

**Comment by kkraune** [comment]
ping @arnej27959

**Comment by arnej27959** [comment]
Yes - we decided to make enabled by default after seeing that it works as intended. So wording here needs to be updated.

**Comment by kkraune** [comment]
thanks, will fix wording!

**Comment by kkraune** [comment]
@arnej27959 PTAL

**Review by jobergum — APPROVED** [review]

**Pull request merged**
