### PR TITLE
rename targetNumHits -> targetHits

### PR DESCRIPTION
**Pull request by arnej27959**
* with note about backwards compatibility

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

@kkraune please review
@geirst @jobergum FYI

### CODE REVIEW

**Comment by jobergum** [comment]
targetNumHits will still be supported until Vespa 8?

**Comment by arnej27959** [comment]
> targetNumHits will still be supported until Vespa 8?

yes, that's the "next major release" - maybe it should say Vespa 8 explicitly?

**Comment by geirst** [comment]
Yes, I think "Vespa 8" is clearer.

**Comment by jobergum** [comment]
Please wait with merging this until the release which supports numHits is out, https://hub.docker.com/r/vespaengine/vespa/tags

**Pull request merged**
