### PR TITLE
bundle JNI

### PR DESCRIPTION
**Pull request by kkraune**
@bratseth maybe as simple as this?

@gjoranv FYI

### CODE REVIEW

**Comment by bratseth** [comment]
great

**Comment by gjoranv** [comment]
Do you have a working example? This PR removes a lot of info.

**Comment by bratseth** [comment]
Here's a working example: https://git.corp.yahoo.com/ml/vespa-tensor-serving
But it does not contain anything special, just a dependency which happen to contain an .so.

**Comment by jobergum** [comment]
Agree with @gjoranv, this page had a lot of potential useful information on JNI and now it contains nothing, no examples and leaves a lot to be guessed by the developer. 👎

**Comment by kkraune** [comment]
so, I'm no expert but according to @bratseth the previous would not work anyway? maybe I got it wrong. In that case - feel free to add back the missing

**Comment by gjoranv** [comment]
@bratseth, why didn't this work? I'm quite sure we've assisted customers with that solution earlier. It's the only way a user can make a library available on the classpath. It's not an ideal solution, but since native libs can only be loaded once it's sometimes the only way.

**Comment by bratseth** [comment]
It could work, but not on hosted, and it is misleading - in most cases this is the wrong thing to do.
I'll add back the information about the classpath.

**Comment by bratseth** [comment]
https://github.com/vespa-engine/documentation/pull/187

**Pull request merged**
