### PR TITLE
Default feeding.concurrency is 0.2 nowadays

### PR DESCRIPTION
**Pull request by jobergum**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jobergum** [comment]
No, it's maybe also auto-adjusted? I'm getting 0.5 with vespaengine/vespa, others report 0.2 using rpm.

**Comment by baldersheim** [comment]
hmm, It is 0.5 as default value in Flags.java. I thought that would be the default everywhere.
@geirst Any clue why default is different ?

**Comment by jobergum** [comment]
Could you add your observation @shelliglick ?

**Comment by shelliglick** [comment]
I saw the value is 0.2 in 2 places:
[Github](https://github.com/vespa-engine/vespa/blob/master/searchcore/src/vespa/searchcore/config/proton.def#L484)
Configuration endpoint /config/v2 (CONFIG_SERVER:19071/config/v2/tenant/default/application/default/vespa.config.search.core.proton)
Screen Shot 2022-07-06 at 13 29 12

**Comment by geirst** [comment]
@baldersheim The default in proton.def is 0.2 (https://github.com/vespa-engine/vespa/blob/master/searchcore/src/vespa/searchcore/config/proton.def#L484). Are we using Flags.java at all for self-hosted Vespa?

**Comment by kkraune** [comment]
what is status for this PR?

**Comment by geirst** [comment]
@baldersheim ping

**Comment by geirst** [comment]
I have followed the quick start guide (https://docs.vespa.ai/en/vespa-quick-start.html) using vespaengine/vespa:8.44.22. The feeding concurrency is 0.5.
```
[root@vespa-container /]# vespa-get-config -n vespa.config.search.core.proton -i music/search/cluster.music/0 | grep concurrency
feeding.concurrency 0.5
```

I have also created a Centos Stream 8 container and installed the Vespa rpm myself following this guide https://docs.vespa.ai/en/build-install-vespa.html. In this case the feeding concurrency is also 0.5:
```
[root@vespa-container bin]# ./vespa-get-config -n vespa.config.search.core.proton -i music/search/cluster.music/0 | grep concurrency
feeding.concurrency 0.5
```

Conclusion: The documentation is already correct.

**Pull request closed without merging**
