### PR TITLE
chown /opt/vespa, too

### PR DESCRIPTION
**Pull request by kkraune**
FYI @aressem

### CODE REVIEW

**Comment by aressem** [comment]
Rationale for this ? Seems wrong.

**Comment by kkraune** [comment]
Testing on an EC2 instance with Docker: 

````
$ vespa-deploy prepare .
Uploading application '.' using http://localhost:19071/application/v2/tenant/default/session
Session 3 for tenant 'default' created.
mkdir /opt/vespa/.cloudconfig: permission denied
````

FYI @hmusum

**Comment by aressem** [comment]
The vespa CLI also defaults to writing stuff in $HOME for the vespa user which is /opt/vespa, but for that tool we did set some env variables in the container. Maybe this is possible for vespa-deploy as well so we can avoid writing into /opt/vespa ?

**Comment by kkraune** [comment]
I am all for that, not sure if other things write here, too, we will find out. what do you say, @hmusum ?

**Comment by kkraune** [comment]
Maybe @arnej27959 have input too, he let me know we had to chown but I am not sure what was the original error - maybe user complaint?

**Comment by arnej27959** [comment]
the original complaint was very confused but indicated some directories had wrong user.
we should document how to fix ownership of any volumes etc mounted into the docker container (if needed).
/opt/vespa should not need to be writable, so we should fix that failure somehow.

Various tools (including vespa-deploy) expect to be able to write to the home directory of the current user;
maybe we should add a /opt/vespa/home owned by vespa and have that as the home directory?

**Comment by kkraune** [comment]
I have created https://github.com/vespa-engine/vespa/issues/26473 to fix the software instead

**Pull request closed without merging**
