### PR TITLE
Go to 2G

### PR DESCRIPTION
**Pull request by jobergum**
@bratseth

### CODE REVIEW

**Comment by jobergum** [comment]
cc @kkraune

**Comment by bratseth** [comment]
Since 2Gb is default, perhaps we could say "(default memory allocation (2Gb) is ok)", or perhaps better yet, just remove the sentence?

**Comment by jobergum** [comment]
Gonna

**Comment by kkraune** [comment]
it is great if 2G suffices!

I added 4G last winter when testing docker install but work has been done since to cut memory usage

**Comment by jobergum** [comment]
Forget this and see https://github.com/vespa-engine/documentation/pull/112

**Pull request closed without merging**
