### PR TITLE
Work outside docker container

### PR DESCRIPTION
**Pull request by frodelu**
@jobergum : My suggestion is to avoid exec'ing inside the Docker container. This example lets you work outside.

### CODE REVIEW

**Comment by jobergum** [comment]
Yes, an alternative is to use http api's and export configuration server port and then use the REST configuration server api'. Then we won't need any docker exec at all but then there is a little more complex instructions.

**Comment by frodelu** [comment]
Yes, that's an alternative, but I thought this was a decent compromise between the two approaches. 😄

**Comment by kkraune** [comment]
it is a good compromise, the deployment URLs do not look good, this is better

**Comment by jobergum** [comment]
Let us consolidate feedback but I think I agree as this as a reasonable
compromise. Maybe it all gets replaced with one big shell script next week.

**Pull request merged**
