### PR TITLE
Remove internal dev docs about config from the sidebar.

### PR DESCRIPTION
**Pull request by gjoranv**
FYI: @hmusum

### CODE REVIEW

**Comment by kkraune** [comment]
I agree that we should not have internal docs in the sidebar. We have also had requests that _all_ docs should be navigable. so maybe these docs belong elsewhere?

**Comment by gjoranv** [comment]
internal docs in a ´legacy/7/´ folder perhaps?

**Comment by kkraune** [comment]
we do that for the company internal docs, so an option. but this is not vespa 7 legacy, it is current? I am just pondering whether we should have a folder for vespa developers (open source) where we put such docs. I'll raise the discussion in the ticket meeting today

**Comment by gjoranv** [comment]
If these docs are not maintained, they will become legacy. For example, many types will move to a new Java package for Vespa 8. I'm not sure it's worth the effort to maintain them. @hmusum ?

**Comment by hmusum** [comment]
I think parts of this is worth keeping as developer doc, but some can be internal only (e.g. the C++ doc will be used by vespa developers only), let's discuss in ticket meeting.

**Comment by kkraune** [comment]
@gjoranv  or @hmusum  please merge

**Review by hmusum — APPROVED** [review]

**Pull request merged**
