### PR TITLE
Remove alias from doc

### PR DESCRIPTION
**Pull request by kkraune**

### CODE REVIEW

**Comment by hmusum** [comment]
I thought alias was a feature, are we dropping it?

**Review by hmusum — APPROVED** [review]
OK, found explanation in a ticket, looks good

**Comment by hmusum** [comment]
Someone might want to know how to use another name for a field, I hope that is explained in doc

**Comment by bratseth** [comment]
We shouldn't remove aliases (on fields), only creating indexes and attributes as logically separate entities with different names., They should always be named the same as the fields in which they are contained (and so of course also have the same aliases as it).

**Comment by kkraune** [comment]
Good clarification, I will modify this PR

**Comment by kkraune** [comment]
alias now only documented for field, with a simple example - @hmusum ptal

**Review by hmusum — APPROVED** [review]
👍

**Pull request merged**
