### PR TITLE
Suggested new format for query guide

### PR DESCRIPTION
**Pull request by kkraune**
- I want to make the query guide more accessible, with live examples for easier experimentation
- Here using Vespa documentation search, but can be anything that is always up
- Queries are in clear text (no urlencoding), click button to expand a pre with a curl command. Can add a copy button to the pre with the curl for easier copy.
- Hence much easier to add query examples in HTML code
- This is a draft for your feedback - if OK, can remove the existing and replace with this / something nicer :-)

queries

CC aesthetics committee @bratseth @frodelu

### CODE REVIEW

**Comment by bratseth** [comment]
Yes, agreed we should move the repeated curl stuff asap. Also because people will use Vespa CLI now instead of curl.

**Comment by bratseth** [comment]
Not sure we need the "expand" or something like that - could just be one single example with curl somewhere (if at all), it's completely orthogonal to formulating YQL.

**Comment by kkraune** [comment]
Yes, happy to let the curl stuff go - it is a good idea to just have one example at the end with how to take the clear text YQL string and curl using
````
curl --data-urlencode ...
````
That will make the doc cleaner, too

**Comment by kkraune** [comment]
... together with a vespa-cli example as well, of course

**Comment by jobergum** [comment]
Looks good, I'm not sure what it expands to? A curl command or a link?

**Comment by kkraune** [comment]
A curl command. But I will move this to one example in a separate section. Thanks for feedback!

**Pull request merged**
