### PR TITLE
Get less hits

### PR DESCRIPTION
**Pull request by kkraune**
- lets see how much faster then

### CODE REVIEW

**Review by frodelu — APPROVED** [review]
OK with me, but wouldn't this mess up pagination? So we'll show only the first 25 results?

**Comment by kkraune** [comment]
good point. we don't have pagination, btw. 25 hits vs 250 hits is approx 500ms faster. need to make more changes, too, as #hits is not right displayed. let me think more

**Comment by kkraune** [comment]
more complicated than I thought, as the search recommendations are mixed into this as well. so "hits" displayed is just a count of all hits in documentation, which is only correct if we always ask for more hits than docs ...

number of hits is not that important, so lets just drop if for now and experiment with getting less hits - and think of adding pagination if we need to

**Comment by kkraune** [comment]
so lets test this - should be snappier. look at pagination if we need to later

**Pull request merged**
