### PR TITLE
Remove "Welcome" link

### PR DESCRIPTION
**Pull request by kkraune**
- this has the same purpose as clicking the logo a few pixles above
  so I don't see a need for it
- maybe I am missing something, though, feel free to comment

@ldalves please merge

### CODE REVIEW

**Comment by ldalves** [comment]
Per the original design from Marco, we should have it... IMHO, the "looking and feel" is better starting with it on the left sidebar, but I'm ok if decide to remove it. 

@frodelu, what's your opinion here? 

I think what we should not have is the "/documentation" in the url, since "http://docs.vespa.ai/" and "http://docs.vespa.ai/documentation/" seems redundant.

**Comment by bratseth** [comment]
> I think what we should not have is the "/documentation" in the url, since "http://docs.vespa.ai/" and "http://docs.vespa.ai/documentation/" seems redundant.

I don't think gh supports any url rewriting, so to avoid that we need to put all the documents in the root of https://github.com/vespa-engine/documentation ... I think that will be a bit messy.

**Comment by ldalves** [comment]
Jekyll has a redirect plugin https://github.com/jekyll/jekyll-redirect-from that could be used, but in tests it shows "redirecting..." when accessing the target link.. then it's not nice. 

Agree that putting all the documents in the root, as we have them now, would be a bit messy... We would need to better organize/group them in "main" folders first...

**Comment by bratseth** [comment]
> We would need to better organize/group them in "main" folders first...

Yes, we could move everything else to e.g site/
and then move the documents up.

**Comment by kkraune** [comment]
decision: we will keep the Welcome, but please change the logo link to point to the frontpage, @ldalves

**Comment by bratseth** [comment]
>  but please change the logo link to point to the frontpage

Just to ensure there is no misunderstanding: The logo should link to http://vespa.ai

**Comment by ldalves** [comment]
done: https://github.com/vespa-engine/documentation/pull/93

**Pull request closed without merging**
