### PR TITLE
Link to exact match alternative + query example

### PR DESCRIPTION
**Pull request by kkraune**
- it is easy to get the encoding wrong when testing ...

### CODE REVIEW

**Comment by kkraune** [comment]
maybe I missed your point - I made this for cut and paste from the generated YQL that I think you can just use - or run the curl command

**Comment by bratseth** [comment]
But if you copy and paste into the command line it'll be wrong?

**Comment by bratseth** [comment]
`vespa query -v 'select * from items where product contains "M&amp;M"`

is copied as "curl etc."?

**Comment by kkraune** [comment]
yql

I'm not sure I understand the problem - when you copy from the page the text copies as is - both the vespa cli command and the url

**Comment by bratseth** [comment]
Yes, right, no problem. :-)

**Review by bratseth — APPROVED** [review]

**Pull request merged**
