### PR TITLE
Remove unsupported TensorFlow page

### PR DESCRIPTION
**Pull request by thigm85**
I deleted the `tensorflow.md` because we no longer support it in Vespa 8. 

Do I need to manually remove it from the main page sidebar? @bratseth @kkraune 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by kkraune — APPROVED** [review]
thanks! yes, please also remove from _data/sidebar.yml

**Review by kkraune — APPROVED** [review]

**Comment by jobergum** [comment]
But we can keep it and instead link and show examples for how to export to ONNX ?

**Comment by thigm85** [comment]
> But we can keep it and instead link and show examples for how to export to ONNX?

We can do that, but should we have pages for PyTorch -> ONNX, JAX --> ONNX, and so on?

I can leave this PR open for now, spend some time creating LTR examples with different frameworks, and then translate that to documentation pages.

**Comment by thigm85** [comment]
I wrote an end-to-end pyvespa [tutorial about Vespa and Tensorflow](https://pyvespa.readthedocs.io/en/latest/use_cases/tensorflow-via-onnx.html) Should we use that or parts of that in `tensorflow.md` page? @kkraune @jobergum @bratseth

**Comment by bratseth** [comment]
Sounds good to me, maybe just a short explanation and a link to it?

**Comment by thigm85** [comment]
> Sounds good to me, maybe just a short explanation and a link to it?

Done.

**Review by kkraune — APPROVED** [review]
great!

**Comment by thigm85** [comment]
@kkraune the link-checker is failing for reasons unrelated to this PR. Should I ignore it?

**Comment by kkraune** [comment]
yes please ignore, I'll fix the links

**Pull request merged**
