### PR TITLE
Make copy and paste behavoir for commands in quick start easier

### PR DESCRIPTION
**Pull request by smorgrav**
An alternative method would be to make the $ sign unselectable

### CODE REVIEW

**Comment by smorgrav** [comment]
Did a small survey and most people prefer the force select on the actual command. For obvious parts that would make sense to break up you can use multiple spans or make the $ sign unselectable as earlier noted.

**Comment by kkraune** [comment]
ok with me, no strong opinions, merge at will (there are conflicts to resolve first)

**Comment by jobergum** [comment]
@smorgrav please consider doing this for all 4 quick starts then, if you think this really helps on the user experience.

**Comment by kkraune** [comment]
close or merge, @smorgrav ?

**Pull request closed without merging**
