### PR TITLE
maxdiskbloatfactor is no longer used.

### PR DESCRIPTION
**Pull request by baldersheim**

### CODE REVIEW

**Comment by kkraune** [comment]
thanks for keeping the doc up to date! a few more is needed:

document-summaries.html:    <a href="content/setup-proton-tuning.html#summary"><em>maxdiskbloatfactor</em></a>.</li>
document-summaries.html:        &lt;maxdiskbloatfactor&gt;0.2&lt;/maxdiskbloatfactor&gt;
proton.html:        <a href="content/setup-proton-tuning.html#summary-store-logstore-maxdiskbloatfactor">
proton.html:        maxdiskbloatfactor</a>.

**Comment by baldersheim** [comment]
Not completed yet. Did not figure out the edit on the web stuff. Need to get back to vi first.

**Comment by baldersheim** [comment]
@kkraune PR

**Comment by kkraune** [comment]
great!

**Pull request merged**
